// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqlcaznakbdvijnwpstg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxbGNhem5ha2Jkdmlqbndwc3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTUyMzksImV4cCI6MjA2NTEzMTIzOX0.77dgeZJy2-SJKLpRYJQRS-PvhL95iS45fgUEerojcCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);